[project]
name = "openlinktoken"
version = "2.1.2"
requires-python = ">=3.10"
dynamic = [
  "authors",
  "description",
  "optional-dependencies",
  "readme",
  "urls",
]
dependencies = [
  "cryptography==50.0.0",
  "jwcrypto==1.5.8",
  "pycryptodome==3.23.0",
  "PyYAML==6.0.3",
]

[build-system]
requires = ["setuptools==84.0.0", "wheel==0.47.0"]
build-backend = "setuptools.build_meta"
